import { DEMO_ROWS, esc, inferType, parseAny, toNumber } from '../../shared/data.js';

const $ = (id) => document.getElementById(id);
const state = { rows: DEMO_ROWS.map(row => ({ ...row })), datasetName: 'Muestra arqueológica local', columns: [], visible: [], result: [] };

function setStatus(message, error = false) { $('status').textContent = message; $('status').style.color = error ? 'var(--red)' : ''; }
function escapeCsv(value) { const text = value === null || value === undefined ? '' : String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
function format(value) { return Number(value).toLocaleString('es-ES', { maximumFractionDigits: 2 }); }
function valuesFor(key) { return state.rows.map(row => row[key]); }
function rebuildFields() { const keys = [...new Set(state.rows.flatMap(row => Object.keys(row)))]; state.columns = keys.map(name => ({ name, type: inferType(valuesFor(name)) })); const dimensions = state.columns; const numeric = state.columns.filter(column => column.type === 'number'); $('dimension').innerHTML = dimensions.length ? dimensions.map(column => `<option value="${esc(column.name)}">${esc(column.name)}</option>`).join('') : '<option value="">Sin campos</option>'; $('measure').innerHTML = '<option value="__count">(recuento de filas)</option>' + numeric.map(column => `<option value="${esc(column.name)}">${esc(column.name)}</option>`).join(''); const preferred = state.columns.find(column => /province|provincia|category|categoría|zona|status/i.test(column.name)) || dimensions.find(column => column.type !== 'number') || dimensions[0]; if (preferred) $('dimension').value = preferred.name; const preferredMeasure = numeric.find(column => !/^(id|latitude|longitude)$/i.test(column.name)) || numeric[0]; if (preferredMeasure) $('measure').value = preferredMeasure.name; updateAggregationOptions(); }
function updateAggregationOptions() { const isCount = $('measure').value === '__count'; $('aggregation').innerHTML = isCount ? '<option value="count">Recuento</option>' : '<option value="sum">Suma</option><option value="average">Media</option><option value="count">Recuento</option><option value="min">Mínimo</option><option value="max">Máximo</option>'; if (isCount) $('aggregation').value = 'count'; }
function filteredRows() { const query = $('search').value.trim().toLowerCase(); return state.rows.filter(row => !query || Object.values(row).some(value => String(value ?? '').toLowerCase().includes(query))); }
function aggregate(rows) { const dimension = $('dimension').value; const measure = $('measure').value; const aggregation = $('aggregation').value; const groups = new Map(); rows.forEach(row => { const key = row[dimension] === null || row[dimension] === undefined || String(row[dimension]).trim() === '' ? '(sin valor)' : String(row[dimension]); if (!groups.has(key)) groups.set(key, { key, count: 0, values: [] }); const group = groups.get(key); group.count += 1; if (measure !== '__count') { const number = toNumber(row[measure]); if (number !== null) group.values.push(number); } }); return [...groups.values()].map(group => { const values = group.values; let value = group.count; if (measure !== '__count' && aggregation === 'sum') value = values.reduce((sum, number) => sum + number, 0); if (measure !== '__count' && aggregation === 'average') value = values.length ? values.reduce((sum, number) => sum + number, 0) / values.length : null; if (measure !== '__count' && aggregation === 'min') value = values.length ? Math.min(...values) : null; if (measure !== '__count' && aggregation === 'max') value = values.length ? Math.max(...values) : null; return { key: group.key, count: group.count, value }; }).filter(row => row.value !== null && Number.isFinite(row.value)).sort((a, b) => b.value - a.value); }
function render() { state.visible = filteredRows(); state.result = aggregate(state.visible); const topN = $('topN').value === 'all' ? state.result.length : Number($('topN').value); const shown = state.result.slice(0, topN); const total = state.result.reduce((sum, row) => sum + row.value, 0); const max = Math.max(0, ...shown.map(row => row.value)); $('visibleCount').textContent = state.visible.length.toLocaleString('es-ES'); $('groupCount').textContent = state.result.length.toLocaleString('es-ES'); $('totalValue').textContent = format(total); $('topGroup').textContent = shown[0]?.key || '—'; $('rowHint').textContent = `${state.rows.length.toLocaleString('es-ES')} filas · ${state.datasetName}`; $('resultHint').textContent = `${shown.length} de ${state.result.length} grupos`; $('valueHead').textContent = $('measure').value === '__count' ? 'Recuento' : $('aggregation').selectedOptions[0].textContent; $('bars').innerHTML = shown.length ? shown.map(row => `<div class="bar-row" role="listitem" aria-label="${esc(row.key)}: ${format(row.value)}"><span class="bar-label" title="${esc(row.key)}">${esc(row.key)}</span><span class="bar-track"><i class="bar-fill" style="width:${max ? Math.max(2, row.value / max * 100) : 0}%"></i></span><span class="bar-value">${format(row.value)}</span></div>`).join('') : '<div class="empty">No hay grupos con los filtros actuales.</div>'; $('tableBody').innerHTML = shown.length ? shown.map(row => `<tr><td>${esc(row.key)}</td><td>${row.count}</td><td>${format(row.value)}</td><td>${total ? format(row.value / total * 100) : '0'}%</td></tr>`).join('') : '<tr><td colspan="4" class="empty">No hay resultados.</td></tr>'; setStatus(`${state.visible.length} filas visibles agrupadas en ${state.result.length} grupos.`); }
function loadRows(rows, name = 'Datos locales') { if (!rows.length) throw new Error('No se encontraron filas analizables.'); if (rows.length > 100000) throw new Error('Para mantener la interfaz fluida, carga como máximo 100.000 filas.'); state.rows = rows.map(row => ({ ...row })); state.datasetName = name; $('fileName').textContent = name; rebuildFields(); render(); }
function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 700); }
function downloadCsv() { const headers = ['grupo', 'filas', 'valor', 'porcentaje_total']; const total = state.result.reduce((sum, row) => sum + row.value, 0); const rows = [headers, ...state.result.map(row => [row.key, row.count, row.value, total ? row.value / total * 100 : 0])]; download('pivot-lab-summary.csv', rows.map(row => row.map(escapeCsv).join(',')).join('\n'), 'text/csv;charset=utf-8'); }
function downloadConfig() { download('pivot-lab-config.json', JSON.stringify({ dataset: state.datasetName, filter: $('search').value, dimension: $('dimension').value, measure: $('measure').value, aggregation: $('aggregation').value, topN: $('topN').value }, null, 2), 'application/json'); }
function reset() { loadRows(DEMO_ROWS, 'Muestra arqueológica local'); $('search').value = ''; setStatus('16 filas sintéticas listas para explorar.'); }

$('fileInput').addEventListener('change', async () => { const file = $('fileInput').files?.[0]; if (!file) return; if (file.size > 120 * 1024 * 1024) { setStatus('El archivo supera 120 MB; no se abre en esta herramienta local.', true); return; } try { loadRows(parseAny(await file.text(), file.name), file.name); } catch (error) { setStatus(error.message || 'No se pudo leer el archivo.', true); } });
['search', 'topN', 'dimension', 'measure', 'aggregation'].forEach(id => $(id).addEventListener(id === 'search' ? 'input' : 'change', () => { if (id === 'measure') updateAggregationOptions(); render(); }));
$('exampleBtn').addEventListener('click', reset); $('clearBtn').addEventListener('click', reset); $('runBtn').addEventListener('click', render); $('csvBtn').addEventListener('click', downloadCsv); $('jsonBtn').addEventListener('click', downloadConfig);
rebuildFields(); render();
